---
title: Stages
---

## Liste des offres de stages

- [MicreAge](https://microage.ca/quebec/carrieres/) : MicroAge est une entreprise de services informatiques qui offre des solutions technologiques sur mesure pour les entreprises. Elle est situé à Québec. Voici son adresse : _5125 1ere Avenue, Quebec (Quebec) G1H 2V1_

> Pour cette entreprise, une candidature spontanée est possible.
 
- [GDG](https://gdginc.com/emplois/) : GDG est une entreprise de services-conseils en informatique qui offre des solutions technologiques sur mesure pour les entreprises. Elle est situé à Québec. VOici son adresse : _330, rue Saint-Vallier Est, bureau 023
Québec (Québec) G1K 9C5 Canada_

> Pour ces entreprises, une candidature spontanée est possible.

- [MS Solutions](https://carriere.mssolutions.ca/) : MS Solutions offre de nombreux services et produits TI pour les entreprises québécoises, adaptés aux besoins de chaque organisation! Elle est situé à Québec. Voici son adresse : _1035 Avenue Wilfrid-Pelletier, Tour B, Bureau 370, Québec, QC, G1W 0C5_

> Pour cette entreprise, une candifature spontanée est possible.

- [MicroCom](https://microcom.ca/jobs/site-technicien-ti-multisite/) : MicroCom est une entreprise de services informatiques qui offre des solutions technologiques sur mesure pour les entreprises. Elle est situé à Montréal. Voici son adresse : _2019 Rue Moreau, Montréal, QC H1W 2M1_

> Pour cette entreprise, une candidature spontanée est possible.

- [Miracom](https://miracom.ca/) : Miracom est une entreprise de services informatiques qui offre des solutions technologiques sur mesure pour les entreprises. Elle est situé à Québec et Montréal. Voici ses adresses : _601 Avenue du Cénacle Québec (Québec) G1E 6W4_ et _Boulevard Saint-Martin Ouest Laval (Québec) H7T 3C2_

> Pour cette entreprise, afin de postuler, il faut envoyer un courriel à l'adresse suivante : cv@miracom.ca. Voici le lien du pdf pour postuler : [Postuler chez Miracom](https://miracom.ca/Stage.pdf)

- [Solulan](https://solulan.com/) : Une entreprise informatique polyvalente et expérimentée. Vous cherchez l’entreprise informatique parfaite pour accompagner votre entreprise? Solulan est la face cachée qu’il vous faut! Nous proposons tous les services TI gérés, solutions infonuagiques et services de cybersécurité nécessaires au fonctionnement, à la productivité et surtout à la sécurité de votre entreprise. Nos experts certifiés sont là pour vous accompagner dans vos projets technologiques, et ce, depuis 1999. Elle est situé à Québec, Montreéal et Toronto. 

> Pour cette entreprise, une candidature spontanée est possible. Voici le lien pour postuler : [Postuler chez Solulan](https://solulan.zohorecruit.com/jobs/Carri%C3%A8re)

